# Generated by Django 3.1.2 on 2022-09-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='dosage',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
