# Generated by Django 3.1.2 on 2022-09-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_medications_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medications',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
