# Generated by Django 3.1.2 on 2022-09-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0003_medications_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medications',
            old_name='name',
            new_name='med_name',
        ),
    ]
